language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - docker-compose up -d --build

script:
  - docker-compose run app pytest

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/app-image
  - docker push $DOCKER_USERNAME/db-image
