version: '3.9' 
 
services: 
  app: 
    build: 
      context: . 
      dockerfile: Dockerfile.app 
    ports: 
      - "5000:5000" 
    depends_on: 
      - db 
 
  db: 
    build: 
      context: . 
      dockerfile: Dockerfile.db 
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: example 
    ports: 
      - "5432:5432" 

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: